title: Victoria Hung's Homepage
page-top-title: Victoria Hung
top-section-bg-text: Scientist, Science Writer, and Science Editor
home-subtitle: Victoria Hung
copyright-text: '&copy; Victoria Hung 2025. All Rights Reserved.'
